
[.preface]
== Document History

Changes to this Specification are coordinated by the Nautical Information
Provision Working Group, an IHO working group under HSSC. New editions
will be made available via the IHO web site. Maintenance of the Specification
shall conform to IHO Resolution 2/2007 (as amended).

[cols="4",options="unnumbered"]
|===
h| Version Number h| Date h| Approved By h| Purpose

| 1.0.0 | 2022-08-18 | | Draft 1

| 1.0.0 | 2022-08-22 | | Revised Draft 1

| 1.0.0 | 2022-11-25 | RM | Draft 2. Applied feedback from NIPWG after
NIPWG9; additional encoding guidance and figures in various places
in clause 2; value types for simple attributes added in clause 17;
revised description of feature table format; enhanced encoding guidance
and figures for various features in clauses 4-13; added associations
not generated by IHO S-100 toolkit in clauses 5-13.
| 1.0.0 | 2023-01-10 | RM | Clarified encoding remarks for dock areas
respecting S-101 guidance; additional encoding instructions or general
remarks (HarbourAreaAdministrative, HarbourAreaSection, Terminal,
OuterLimit, HarbourBasin); added Location Hours association to HarbourFacility;
document date updated to synchronize with other S-131 artefacts; ToC
regenerated

| | | |
| | | |
| | | |
| | | |
| | | |
| | | |
| | | |

|===
